export const PACKAGES = {
  bike: [
    {
      id: 'br',
      name: 'Basic rinse',
      price: 49,
      time: '15 min',
      tag: null,
      features: ['Water wash', 'Chain rinse', 'Quick wipe'],
    },
    {
      id: 'fb',
      name: 'Full bike wash',
      price: 99,
      time: '25 min',
      tag: 'Popular',
      features: ['Foam wash', 'Chain lube', 'Tyre scrub', 'Seat wipe'],
    },
    {
      id: 'pb',
      name: 'Premium bike',
      price: 199,
      time: '45 min',
      tag: null,
      features: [
        'Full foam',
        'Engine degrease',
        'Polish & shine',
        'Tyre dressing',
      ],
    },
  ],
  car: [
    {
      id: 'qr',
      name: 'Quick rinse',
      price: 69,
      time: '20 min',
      tag: null,
      features: ['Exterior water wash', 'Wheel rinse', 'Window wipe'],
    },
    {
      id: 'es',
      name: 'Essential wash',
      price: 159,
      time: '35 min',
      tag: 'Popular',
      features: [
        'Exterior foam wash',
        'Tyre cleaning',
        'Window clean',
        'Interior vacuum',
      ],
    },
    {
      id: 'pw',
      name: 'Premium wash',
      price: 299,
      time: '60 min',
      tag: null,
      features: [
        'Full foam wash',
        'Interior vacuum + wipe',
        'Dashboard polish',
        'Tyre dressing',
        'Air freshener',
      ],
    },
    {
      id: 'dw',
      name: 'Deep detail wash',
      price: 599,
      time: '90 min',
      tag: 'Best value',
      features: [
        'All Premium +',
        'Engine bay clean',
        'Seat shampoo',
        'Paint protection wax',
        'Ceramic coat prep',
      ],
    },
  ],
  suv: [
    {
      id: 'sr',
      name: 'SUV rinse',
      price: 99,
      time: '25 min',
      tag: null,
      features: ['Exterior rinse', 'Wheel wash', 'Window wipe'],
    },
    {
      id: 'sw',
      name: 'SUV wash',
      price: 249,
      time: '50 min',
      tag: 'Popular',
      features: [
        'Full foam wash',
        'Interior vacuum',
        'Dashboard wipe',
        'Tyre dressing',
      ],
    },
    {
      id: 'sp',
      name: 'SUV premium',
      price: 449,
      time: '75 min',
      tag: null,
      features: ['All wash +', 'Seat shampoo', 'Engine clean', 'Wax coat'],
    },
    {
      id: 'sd',
      name: 'SUV full detail',
      price: 799,
      time: '2 hrs',
      tag: 'Best value',
      features: [
        'Complete detail',
        'Ceramic prep',
        'Paint correction',
        'Odour treatment',
        'Leather conditioning',
      ],
    },
  ],
};
